### ISSUE TITLE
"Unexpected end of JSON input"  but only sometimes

### ISSUE THREAD

**Issue by randall-coding** [gamelaster/opensupports-docker#8]
When I first ran `docker-compose up` the install page would load up fine.  It worked at first today also, but now it fails with a javascript error: 
"Unexpected end of JSON input"

Full output:

> Uncaught SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at e.value (bundle.js:16:4483)
>     at e.value (bundle.js:16:5836)
>     at Object.<anonymous> (bundle.js:16:51110)
>     at C (bundle.js:1:7843)
>     at r (bundle.js:1:559)
>     at Object.<anonymous> (bundle.js:21:4116)
>     at C (bundle.js:1:7843)
>     at r (bundle.js:1:559)
>     at Object.<anonymous> (bundle.js:16:27479)

    
And the line in question on bundle.js is:
```
        }, {
            key: "getDepartments",
            value: function() {
                return JSON.parse(this.getItem("departments"))  #ERROR HERE
            }
        }, {
```

I'm currently trying this on Vivaldi browser.

Restarting with docker-compose up yields the same result.

**Comment by randall-coding** [comment]
Trying a new browser fixes the issue at first.  Refreshing the page yields the same error again.    

The solution right now is to start a new browser window in private mode.

**Comment by switux** [comment]
Same problem here, except that it is systematic. However, switching to private mode browsing, as suggested (thanks btw, saved my day ...) solves the issue.
